This is the way
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-leeKol pull request #1
Opened 2022-03-19 20:09 UTC by leeKol

Hi, I'd love for your review.

2022-03-20 16:25 UTC, itayday commented on this_is_the_way.py
> +
Great job!

2022-03-25 18:57 UTC, talbarfm requested changes

2022-03-25 18:57 UTC, talbarfm commented on this_is_the_way.py
> +    return [os.path.basename(file) for file in glob.glob(path + "/deep*")]
Nice! glob is my favorite directory to get paths with

2022-03-25 18:57 UTC, talbarfm commented on this_is_the_way.py
> +def get_deep_files(path):
Use type hints and return types

2022-03-25 18:57 UTC, talbarfm commented on this_is_the_way.py
> +    return [os.path.basename(file) for file in glob.glob(path + "/deep*")]
You have a small bug here - what If I had a directory names deepurple? whould it it return? is it a file?

2022-03-31 06:52 UTC, lovodkin93 approved these changes

2022-03-31 06:52 UTC, merged