The i_have_no_vinaigrette exercise is done.
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-leeKol pull request #2
Opened 2022-03-19 23:25 UTC by leeKol

Hi, I'd love for your review.

2022-03-20 16:28 UTC, itayday commented on i_have_no_vinaigrette.py
> +random_date = get_random_date()
If you want to call your functions please do it inside a main function.

2022-03-24 04:04 UTC, talbarfm requested changes
Really nice job!

2022-03-24 04:04 UTC, talbarfm commented on i_have_no_vinaigrette.py
> +    """
Nice documentation! good job! 
read the relevant parts of this document - add type hints and return types

2022-03-24 04:04 UTC, talbarfm commented on i_have_no_vinaigrette.py
> +    """
![Capture](https://user-images.githubusercontent.com/13467749/159839801-546a5447-18fb-4142-aafd-4c18b5309b8c.JPG)
should look like this

2022-03-24 04:04 UTC, talbarfm commented on i_have_no_vinaigrette.py
> +    return date.weekday() == 0
Nice! even though its a small function, I would do the same thing because it makes the code way more readable :) good job!

2022-03-31 06:52 UTC, lovodkin93 approved these changes
well done! the code looks very good and well-documented,

2022-03-31 06:52 UTC, merged