The piece_of_cake exercise is done.
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-leeKol pull request #4
Opened 2022-03-20 05:56 UTC by leeKol

Hi, I'd love for your review.

2022-03-20 16:35 UTC, itayday commented on piece_of_cake.py
> +    price = 0
I think that you should rename the variable price (it does not indicate that it it the total price).

2022-03-25 14:17 UTC, talbarfm requested changes
Good job!!!

2022-03-25 14:17 UTC, talbarfm commented on piece_of_cake.py
> +    The function can get a list of ingredients that should be ignored when calculating.
Nice documentation!!!

2022-03-25 14:17 UTC, talbarfm commented on piece_of_cake.py
> +    for key in prices:
You can use reduce for this, and reduce this to one line

2022-03-25 14:17 UTC, talbarfm commented on piece_of_cake.py
> +            price += prices.get(key) * int(quantities.get(key)/100)
spaces aound operators

2022-03-31 06:49 UTC, lovodkin93 approved these changes
good job!

2022-03-31 06:49 UTC, merged